import { Tooltip } from 'antd'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Freelance marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='text-red-500'>
          <Tooltip title="Hello">
            <div className='bg-red-800'>hello</div>
          </Tooltip>
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
