import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
const home = () => {
  return (
    <div>
      <Head>
        <title>Freelance marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/home">Home</Link>
    </div>
  );
};

export default home;